"""
JSON / CSV Exporter

Serializes mechanism parameters and results into downloadable formats.
"""

import io
import json
from typing import Dict


def mechanism_to_csv_bytes(data: Dict) -> bytes:
    """
    Convert mechanism data to CSV format.

    Sections:
      1. Mechanism Parameters
      2. Error Metrics
      3. Performance Checks
      4. Coupler Curve Points (if present)

    Returns:
        CSV content as bytes
    """
    lines = []

    # Header
    lines.append("# Zxynth Mechanism Synthesis Report")
    lines.append("# Generated by zxynth.xyz")
    lines.append("")

    # Mechanism Parameters
    mech = data.get("mechanism", {})
    if mech:
        lines.append("# Mechanism Parameters")
        lines.append("Parameter,Value,Unit")

        param_list = [
            ("type", mech.get("type", ""), ""),
            ("a1_ground", mech.get("a1"), ""),
            ("a2_crank", mech.get("a2"), ""),
            ("a3_coupler", mech.get("a3"), ""),
            ("a4_rocker", mech.get("a4"), ""),
            ("p_coupler_point_dist", mech.get("p"), ""),
            ("alpha_coupler_point_angle", mech.get("alpha"), "deg"),
            ("pivot_A_x", mech.get("pivotA", [None])[0] if mech.get("pivotA") else None, ""),
            ("pivot_A_y", mech.get("pivotA", [None, None])[1] if mech.get("pivotA") else None, ""),
            ("pivot_D_x", mech.get("pivotD", [None])[0] if mech.get("pivotD") else None, ""),
            ("pivot_D_y", mech.get("pivotD", [None, None])[1] if mech.get("pivotD") else None, ""),
            ("ground_angle", mech.get("groundAngle"), "deg"),
            ("grashof_margin", mech.get("grashofMargin"), ""),
        ]

        for name, val, unit in param_list:
            if val is not None:
                lines.append(f"{name},{val},{unit}")

        lines.append("")

    # Error Metrics
    metrics = data.get("errorMetrics", {})
    if metrics:
        lines.append("# Error Metrics")
        lines.append("Metric,Value,Percent")

        for key in ["mean", "max", "rms"]:
            val = metrics.get(key, "")
            pct = metrics.get(f"{key}Percent", "")
            lines.append(f"{key}_error,{val},{pct}")

        lines.append("")

    # Performance
    grashof = data.get("grashofType") or mech.get("grashofType")
    trans = data.get("transmissionAngle")
    if grashof or trans:
        lines.append("# Performance")
        lines.append("Check,Value")
        if grashof:
            lines.append(f"grashof_type,{grashof}")
        if trans and isinstance(trans, dict):
            lines.append(f"transmission_angle_min,{trans.get('min', '')}")
            lines.append(f"transmission_angle_max,{trans.get('max', '')}")
        lines.append("")

    # Coupler Curve Points
    curve = data.get("couplerCurve", [])
    if curve and len(curve) > 0:
        lines.append("# Coupler Curve Points")
        lines.append("x,y")
        for pt in curve:
            if isinstance(pt, (list, tuple)) and len(pt) >= 2:
                lines.append(f"{pt[0]:.6f},{pt[1]:.6f}")
        lines.append("")

    # Desired Path Points
    desired = data.get("desiredPath", [])
    if desired and len(desired) > 0:
        lines.append("# Desired Path Points")
        lines.append("x,y")
        for pt in desired:
            if isinstance(pt, (list, tuple)) and len(pt) >= 2:
                lines.append(f"{pt[0]:.6f},{pt[1]:.6f}")

    content = "\n".join(lines)
    return content.encode("utf-8")


def mechanism_to_json_bytes(data: Dict) -> bytes:
    """
    Convert mechanism data to formatted JSON.

    Returns:
        JSON content as bytes
    """
    # Clean up data for JSON serialization
    clean = _clean_for_json(data)

    output = {
        "generator": "Zxynth (zxynth.xyz)",
        "version": "1.0.0",
        **clean,
    }

    content = json.dumps(output, indent=2, default=str)
    return content.encode("utf-8")


def _clean_for_json(obj):
    """Recursively clean data for JSON serialization."""
    if isinstance(obj, dict):
        return {k: _clean_for_json(v) for k, v in obj.items() if v is not None}
    elif isinstance(obj, (list, tuple)):
        return [_clean_for_json(item) for item in obj]
    elif isinstance(obj, float):
        if obj != obj:  # NaN check
            return None
        if abs(obj) == float("inf"):
            return None
        return round(obj, 6)
    elif hasattr(obj, "tolist"):  # numpy array
        return obj.tolist()
    return obj
