"""
PDF Report Generator

Generates a comprehensive PDF report of the synthesis results.
Two modes:
  - 'full': Educational report with theory, step-by-step derivations,
    equations, diagrams, and complete results
  - 'concise': Summary with key parameters, error metrics, and mechanism diagram

Uses ReportLab for PDF generation.
"""

import io
import math
from typing import Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, Image,
)
from reportlab.graphics.shapes import Drawing, Line, Circle, String, Rect
from reportlab.graphics import renderPDF


def generate_pdf_bytes(data: Dict, mode: str = "full") -> bytes:
    """
    Generate PDF report as bytes.

    Args:
        data: export data dict (mechanism, errorMetrics, couplerCurve, etc.)
        mode: 'full' or 'concise'

    Returns:
        PDF file content as bytes
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=25 * mm, bottomMargin=20 * mm,
    )

    styles = _build_styles()
    story = []

    # Title page
    story.extend(_build_title_page(styles, data))
    story.append(PageBreak())

    if mode == "full":
        # Full educational report
        story.extend(_build_theory_section(styles))
        story.append(PageBreak())
        story.extend(_build_type_synthesis_section(styles, data))
        story.extend(_build_number_synthesis_section(styles, data))
        story.append(PageBreak())

    # Results section (both modes)
    story.extend(_build_results_section(styles, data))
    story.extend(_build_error_section(styles, data))
    story.extend(_build_performance_section(styles, data))

    if mode == "full":
        story.extend(_build_equations_section(styles))

    # Footer info
    story.extend(_build_footer(styles))

    doc.build(story)
    return buffer.getvalue()


def _build_styles() -> Dict:
    """Create custom paragraph styles."""
    base = getSampleStyleSheet()

    styles = {
        "title": ParagraphStyle(
            "ZxynthTitle", parent=base["Title"],
            fontSize=24, spaceAfter=6 * mm, textColor=colors.HexColor("#3170e3"),
        ),
        "subtitle": ParagraphStyle(
            "ZxynthSubtitle", parent=base["Normal"],
            fontSize=12, textColor=colors.HexColor("#94a3b8"),
            spaceAfter=10 * mm,
        ),
        "h1": ParagraphStyle(
            "ZxynthH1", parent=base["Heading1"],
            fontSize=16, spaceAfter=4 * mm, spaceBefore=8 * mm,
            textColor=colors.HexColor("#1e4da8"),
        ),
        "h2": ParagraphStyle(
            "ZxynthH2", parent=base["Heading2"],
            fontSize=13, spaceAfter=3 * mm, spaceBefore=5 * mm,
            textColor=colors.HexColor("#2a60c8"),
        ),
        "body": ParagraphStyle(
            "ZxynthBody", parent=base["Normal"],
            fontSize=10, leading=14, spaceAfter=3 * mm,
        ),
        "mono": ParagraphStyle(
            "ZxynthMono", parent=base["Code"],
            fontSize=9, leading=12, fontName="Courier",
            backColor=colors.HexColor("#f1f5f9"),
            borderPadding=4,
        ),
        "equation": ParagraphStyle(
            "ZxynthEq", parent=base["Normal"],
            fontSize=11, alignment=TA_CENTER, fontName="Courier-Bold",
            spaceAfter=4 * mm, spaceBefore=3 * mm,
            textColor=colors.HexColor("#1e4da8"),
        ),
        "small": ParagraphStyle(
            "ZxynthSmall", parent=base["Normal"],
            fontSize=8, textColor=colors.HexColor("#64748b"),
        ),
        "caption": ParagraphStyle(
            "ZxynthCaption", parent=base["Normal"],
            fontSize=9, alignment=TA_CENTER, textColor=colors.HexColor("#64748b"),
            spaceAfter=5 * mm,
        ),
    }
    return styles


def _build_title_page(styles, data) -> list:
    """Build the title page."""
    story = []
    story.append(Spacer(1, 40 * mm))
    story.append(Paragraph("ZXYNTH", styles["title"]))
    story.append(Paragraph("Planar Mechanism Synthesis Report", styles["subtitle"]))
    story.append(Spacer(1, 10 * mm))

    # Metadata table
    meta = data.get("options", {})
    mech = data.get("mechanism", {})
    mech_type = mech.get("type", "four_bar").replace("_", " ").title()

    info_data = [
        ["Mechanism Type", mech_type],
        ["Generated By", "Zxynth — zxynth.xyz"],
        ["Author", "Sankar Balasubramanian"],
    ]

    t = Table(info_data, colWidths=[50 * mm, 90 * mm])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#64748b")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(t)
    return story


def _build_theory_section(styles) -> list:
    """Build the theory/education section (full mode only)."""
    story = []
    story.append(Paragraph("1. Mechanism Synthesis Theory", styles["h1"]))

    story.append(Paragraph("1.1 The Three Classical Problems", styles["h2"]))
    story.append(Paragraph(
        "Mechanism synthesis addresses three fundamental problems: "
        "<b>Path Generation</b> (coupler point traces a prescribed curve), "
        "<b>Function Generation</b> (output angle is a function of input angle), and "
        "<b>Motion Generation</b> (coupler link passes through prescribed positions and orientations).",
        styles["body"],
    ))

    story.append(Paragraph("1.2 Degrees of Freedom", styles["h2"]))
    story.append(Paragraph(
        "The mobility of a planar mechanism is computed using Gruebler's equation:",
        styles["body"],
    ))
    story.append(Paragraph("F = 3(n - 1) - 2j₁ - j₂", styles["equation"]))
    story.append(Paragraph(
        "where n = total links, j₁ = lower pairs (revolute + prismatic), j₂ = higher pairs. "
        "For single-input mechanisms, we require F = 1.",
        styles["body"],
    ))

    story.append(Paragraph("1.3 Synthesis Stages", styles["h2"]))
    story.append(Paragraph(
        "<b>Type Synthesis:</b> Select mechanism family (linkage, cam, gear). "
        "<b>Number Synthesis:</b> Determine link/joint count, verify DOF. "
        "<b>Dimensional Synthesis:</b> Compute exact link lengths and pivot locations "
        "using analytical methods (Freudenstein, Burmester) or global optimization (DE, GA, PSO, SA).",
        styles["body"],
    ))

    return story


def _build_type_synthesis_section(styles, data) -> list:
    """Build type synthesis section."""
    story = []
    story.append(Paragraph("2. Type Synthesis", styles["h1"]))
    mech = data.get("mechanism", {})
    mech_type = mech.get("type", "four_bar")

    story.append(Paragraph(
        f"The selected mechanism type is <b>{mech_type.replace('_', ' ').title()}</b>. "
        "Planar linkages are preferred for path, function, and motion generation "
        "because they provide smooth, continuous motion with a single degree of freedom.",
        styles["body"],
    ))
    return story


def _build_number_synthesis_section(styles, data) -> list:
    """Build number synthesis section with Gruebler calculation."""
    story = []
    story.append(Paragraph("3. Number Synthesis", styles["h1"]))

    mech = data.get("mechanism", {})
    mech_type = mech.get("type", "four_bar")

    configs = {
        "four_bar": (4, 4, 0),
        "six_bar_watt": (6, 7, 0),
        "six_bar_stephenson": (6, 7, 0),
        "slider_crank": (4, 4, 0),
    }
    n, j1, j2 = configs.get(mech_type, (4, 4, 0))
    dof = 3 * (n - 1) - 2 * j1 - j2

    story.append(Paragraph("Gruebler's Equation Verification:", styles["body"]))
    story.append(Paragraph(f"F = 3({n} - 1) - 2({j1}) - {j2} = {dof}", styles["equation"]))
    story.append(Paragraph(
        f"DOF = {dof} {'✓ (single-input mechanism)' if dof == 1 else '✗ (invalid)'}",
        styles["body"],
    ))
    return story


def _build_results_section(styles, data) -> list:
    """Build the mechanism parameters results section."""
    story = []
    story.append(Paragraph("Mechanism Parameters", styles["h1"]))

    mech = data.get("mechanism", {})
    if not mech:
        story.append(Paragraph("No mechanism data available.", styles["body"]))
        return story

    # Parameters table
    params = []
    param_map = [
        ("a₁ (ground)", "a1"), ("a₂ (crank)", "a2"),
        ("a₃ (coupler)", "a3"), ("a₄ (rocker)", "a4"),
        ("p (coupler pt distance)", "p"), ("α (coupler pt angle)", "alpha"),
    ]

    for label, key in param_map:
        val = mech.get(key)
        if val is not None:
            unit = "°" if "angle" in label.lower() or "α" in label else ""
            params.append([label, f"{val:.4f}{unit}"])

    if mech.get("pivotA"):
        pa = mech["pivotA"]
        params.append(["Pivot A", f"({pa[0]:.2f}, {pa[1]:.2f})"])
    if mech.get("pivotD"):
        pd = mech["pivotD"]
        params.append(["Pivot D", f"({pd[0]:.2f}, {pd[1]:.2f})"])

    if params:
        t = Table(
            [["Parameter", "Value"]] + params,
            colWidths=[70 * mm, 60 * mm],
        )
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e4da8")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("FONTNAME", (1, 1), (1, -1), "Courier"),
        ]))
        story.append(t)
        story.append(Spacer(1, 5 * mm))

    return story


def _build_error_section(styles, data) -> list:
    """Build error metrics section."""
    story = []
    metrics = data.get("errorMetrics")
    if not metrics:
        return story

    story.append(Paragraph("Error Analysis", styles["h1"]))

    error_data = [
        ["Metric", "Value", "% of Extent"],
        ["Mean Error", f"{metrics.get('mean', 0):.4f}", f"{metrics.get('meanPercent', 0):.2f}%"],
        ["Max Error", f"{metrics.get('max', 0):.4f}", f"{metrics.get('maxPercent', 0):.2f}%"],
        ["RMS Error", f"{metrics.get('rms', 0):.4f}", f"{metrics.get('rmsPercent', 0):.2f}%"],
    ]

    t = Table(error_data, colWidths=[50 * mm, 40 * mm, 40 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#059669")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("FONTNAME", (1, 1), (-1, -1), "Courier"),
        ("ALIGNMENT", (1, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(t)
    story.append(Spacer(1, 5 * mm))

    return story


def _build_performance_section(styles, data) -> list:
    """Build performance checks section."""
    story = []
    mech = data.get("mechanism", {})

    story.append(Paragraph("Performance & Feasibility", styles["h1"]))

    checks = []
    grashof = mech.get("grashofType") or data.get("grashofType")
    if grashof:
        status = "✓ PASS" if grashof != "non-grashof" else "✗ FAIL"
        checks.append(["Grashof Condition", grashof.replace("-", " ").title(), status])

    trans = data.get("transmissionAngle") or mech.get("transmissionAngle")
    if trans and isinstance(trans, dict):
        min_a = trans.get("min", 0)
        max_a = trans.get("max", 0)
        status = "✓ PASS" if min_a >= 30 else "✗ FAIL"
        checks.append(["Transmission Angle", f"Min: {min_a:.1f}° / Max: {max_a:.1f}°", status])

    margin = mech.get("grashofMargin")
    if margin is not None:
        checks.append(["Grashof Margin", f"{margin:.2f}", ""])

    if checks:
        t = Table(
            [["Check", "Value", "Status"]] + checks,
            colWidths=[50 * mm, 55 * mm, 25 * mm],
        )
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#3170e3")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(t)

    return story


def _build_equations_section(styles) -> list:
    """Build equations appendix (full mode only)."""
    story = []
    story.append(PageBreak())
    story.append(Paragraph("Appendix: Key Equations", styles["h1"]))

    equations = [
        ("Gruebler's Equation", "F = 3(n - 1) - 2j₁ - j₂"),
        ("Loop-Closure (vector)", "r₂ + r₃ = r₁ + r₄"),
        ("Freudenstein's Equation", "R₁·cos(θ₂) - R₂·cos(θ₄) + R₃ = cos(θ₂ - θ₄)"),
        ("Grashof Condition", "s + l ≤ p + q"),
        ("Transmission Angle", "cos(μ) = (a₃² + a₄² - a₁² - a₂² + 2a₁a₂cos(θ₂)) / (2a₃a₄)"),
        ("Chebyshev Spacing", "x_k = (a+b)/2 + (b-a)/2 · cos((2k-1)π / 2n)"),
        ("Closest-Point Error", "f(x) = (1/N) Σ min_j [(Px_j - Dx_k)² + (Py_j - Dy_k)²]"),
    ]

    for name, eq in equations:
        story.append(Paragraph(f"<b>{name}:</b>", styles["body"]))
        story.append(Paragraph(eq, styles["equation"]))

    return story


def _build_footer(styles) -> list:
    """Build report footer."""
    story = []
    story.append(Spacer(1, 10 * mm))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#cbd5e1")))
    story.append(Spacer(1, 3 * mm))
    story.append(Paragraph(
        "Generated by Zxynth (zxynth.xyz) — Planar Mechanism Synthesis Web Application. "
        "Made by Sankar Balasubramanian · linkedin.com/in/sankar4 · sankar.studio",
        styles["small"],
    ))
    story.append(Paragraph("© All Rights Reserved.", styles["small"]))
    return story
