/**
 * Renders the coupler curve trace — the actual path generated by the mechanism.
 *
 * @param {object} props
 * @param {Array<{x:number,y:number}>} props.curve - Coupler curve points (screen coords)
 * @param {number} [props.currentIndex=-1] - Current animation position index (-1 = show full)
 * @param {boolean} [props.visible=true]
 */
export default function CouplerCurveOverlay({
  curve = [],
  currentIndex = -1,
  visible = true,
}) {
  if (!visible || curve.length < 2) return null;

  // If animating, show curve up to current index
  const displayCurve = currentIndex >= 0
    ? curve.slice(0, Math.min(currentIndex + 1, curve.length))
    : curve;

  const polyStr = displayCurve.map((p) => `${p.x},${p.y}`).join(' ');

  // Full curve (faded) when animating
  const fullPolyStr = currentIndex >= 0
    ? curve.map((p) => `${p.x},${p.y}`).join(' ')
    : null;

  return (
    <g className="pointer-events-none">
      {/* Full curve ghost (when animating) */}
      {fullPolyStr && currentIndex >= 0 && (
        <polyline
          points={fullPolyStr}
          fill="none"
          stroke="#34d399"
          strokeWidth={1}
          opacity={0.15}
          strokeLinejoin="round"
        />
      )}

      {/* Active/traced portion */}
      <polyline
        points={polyStr}
        fill="none"
        stroke="#34d399"
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
        opacity={0.85}
      />

      {/* Current position dot */}
      {currentIndex >= 0 && currentIndex < curve.length && (
        <circle
          cx={curve[currentIndex].x}
          cy={curve[currentIndex].y}
          r={5}
          fill="#34d399"
          stroke="var(--color-bg-primary)"
          strokeWidth={2}
        >
          <animate
            attributeName="r"
            values="4;6;4"
            dur="1s"
            repeatCount="indefinite"
          />
        </circle>
      )}

      {/* Start/end markers (when showing full curve) */}
      {currentIndex < 0 && curve.length > 1 && (
        <>
          <circle cx={curve[0].x} cy={curve[0].y} r={4}
            fill="#34d399" stroke="var(--color-bg-primary)" strokeWidth={1.5} opacity={0.7} />
        </>
      )}
    </g>
  );
}
