import { create } from 'zustand';
import axios from 'axios';
import { API, POLLING } from '../config/api';

/**
 * Synthesis Job State Store
 *
 * Manages the synthesis execution lifecycle:
 * - Job submission and ID tracking
 * - Polling for progress (generation, fitness)
 * - Storing results (analytical + optimization)
 * - Cognate mechanisms
 * - Kinematic inversion results
 * - Error handling
 */
const useSynthesisStore = create((set, get) => ({
  // ── Job State ────────────────────────────────────────────────
  /** Current job ID (from backend) */
  jobId: null,
  /** Job status: 'idle' | 'submitting' | 'queued' | 'running' | 'complete' | 'error' */
  status: 'idle',
  /** Error message */
  error: null,

  // ── Progress ─────────────────────────────────────────────────
  /** Current generation/iteration */
  generation: 0,
  /** Max generations */
  maxGenerations: 400,
  /** Current best fitness value */
  bestFitness: null,
  /** Elapsed time in seconds */
  elapsed: 0,
  /** Algorithm name being run */
  runningAlgorithm: '',

  // ── Results ──────────────────────────────────────────────────
  /** Analytical solution (precision-point method) */
  analyticalResult: null,
  /** Optimization solution (best from DE/GA/PSO/SA) */
  optimizationResult: null,
  /** Active result to display: 'analytical' | 'optimization' */
  activeResultView: 'optimization',

  // ── Mechanism Data (from active result) ──────────────────────
  /** Full mechanism parameters */
  mechanism: null,
  /** Coupler curve points generated by the mechanism: [{x, y}] */
  couplerCurve: null,
  /** Error metrics: { mean, max, rms, meanPercent, maxPercent, rmsPercent } */
  errorMetrics: null,
  /** Grashof classification */
  grashofType: null,
  /** Min/max transmission angle */
  transmissionAngle: null,
  /** Defect check results */
  defects: null,

  // ── Cognates ─────────────────────────────────────────────────
  /** Roberts-Chebyshev cognate mechanisms (array of up to 3) */
  cognates: null,
  /** Whether cognates have been computed */
  cognatesLoaded: false,

  // ── Kinematic Inversion ──────────────────────────────────────
  /** Inversion results keyed by fixed link index: { 0: {...}, 1: {...}, ... } */
  inversions: {},
  /** Currently selected inversion (fixed link index) */
  activeInversion: 0,

  // ── Polling Internals ────────────────────────────────────────
  _pollTimer: null,
  _pollCount: 0,
  _startTime: null,

  // ── Actions ──────────────────────────────────────────────────

  /**
   * Submit a synthesis job to the backend.
   * @param {object} request - Synthesis request payload (from path/function/motion store's buildRequest)
   */
  submitJob: async (request) => {
    set({
      status: 'submitting',
      error: null,
      jobId: null,
      generation: 0,
      bestFitness: null,
      elapsed: 0,
      analyticalResult: null,
      optimizationResult: null,
      mechanism: null,
      couplerCurve: null,
      errorMetrics: null,
      cognates: null,
      cognatesLoaded: false,
      inversions: {},
      activeInversion: 0,
      _pollCount: 0,
      _startTime: Date.now(),
      runningAlgorithm: request.algorithm?.toUpperCase() || '',
      maxGenerations: request.hyperparams?.maxGenerations || 400,
    });

    try {
      const response = await axios.post(API.synthesize, request);
      const { jobId } = response.data;

      set({ jobId, status: 'queued' });
      get()._startPolling(jobId);
    } catch (err) {
      const msg = err.response?.data?.detail || err.message || 'Failed to submit job';
      set({ status: 'error', error: msg });
    }
  },

  /** Start polling for job status */
  _startPolling: (jobId) => {
    const poll = async () => {
      const s = get();
      if (s.status === 'complete' || s.status === 'error' || s.status === 'idle') {
        return; // Stop polling
      }

      if (s._pollCount >= POLLING.maxAttempts) {
        set({ status: 'error', error: 'Job timed out — exceeded maximum poll attempts' });
        return;
      }

      try {
        const response = await axios.get(API.jobStatus(jobId));
        const data = response.data;

        const elapsed = s._startTime ? (Date.now() - s._startTime) / 1000 : 0;

        if (data.status === 'running') {
          set({
            status: 'running',
            generation: data.generation || s.generation,
            bestFitness: data.bestFitness ?? s.bestFitness,
            elapsed,
            _pollCount: s._pollCount + 1,
          });
          // Schedule next poll
          setTimeout(poll, POLLING.interval);
        } else if (data.status === 'complete') {
          // Fetch full result
          const resultRes = await axios.get(API.jobResult(jobId));
          const result = resultRes.data;

          set({
            status: 'complete',
            elapsed,
            analyticalResult: result.analytical || null,
            optimizationResult: result.optimization || null,
            mechanism: result.optimization?.mechanism || result.analytical?.mechanism || null,
            couplerCurve: result.optimization?.couplerCurve || result.analytical?.couplerCurve || null,
            errorMetrics: result.optimization?.errorMetrics || result.analytical?.errorMetrics || null,
            grashofType: result.optimization?.grashofType || null,
            transmissionAngle: result.optimization?.transmissionAngle || null,
            defects: result.optimization?.defects || null,
            cognates: result.cognates || null,
            cognatesLoaded: !!result.cognates,
            generation: s.maxGenerations,
            bestFitness: result.optimization?.errorMetrics?.mean ?? s.bestFitness,
          });
        } else if (data.status === 'error' || data.status === 'failed') {
          set({
            status: 'error',
            error: data.error || 'Synthesis failed',
            elapsed,
          });
        } else {
          // queued or unknown — keep polling
          set({ status: data.status || 'queued', elapsed, _pollCount: s._pollCount + 1 });
          setTimeout(poll, POLLING.interval);
        }
      } catch (err) {
        // Network error — retry with backoff
        const s = get();
        if (s._pollCount < 3) {
          set({ _pollCount: s._pollCount + 1 });
          setTimeout(poll, POLLING.retryDelay);
        } else {
          set({ status: 'error', error: `Connection lost: ${err.message}` });
        }
      }
    };

    // Start first poll
    setTimeout(poll, POLLING.interval);
  },

  /** Switch between analytical and optimization result views */
  setActiveResultView: (view) => {
    const s = get();
    const result = view === 'analytical' ? s.analyticalResult : s.optimizationResult;
    if (result) {
      set({
        activeResultView: view,
        mechanism: result.mechanism || null,
        couplerCurve: result.couplerCurve || null,
        errorMetrics: result.errorMetrics || null,
      });
    } else {
      set({ activeResultView: view });
    }
  },

  /** Set active inversion */
  setActiveInversion: (linkIndex) => set({ activeInversion: linkIndex }),

  /** Store inversion result */
  addInversionResult: (linkIndex, result) =>
    set((s) => ({
      inversions: { ...s.inversions, [linkIndex]: result },
    })),

  /** Cancel current job (stop polling) */
  cancelJob: () => {
    set({ status: 'idle', jobId: null, _pollCount: 0 });
  },

  /** Full reset */
  reset: () =>
    set({
      jobId: null,
      status: 'idle',
      error: null,
      generation: 0,
      maxGenerations: 400,
      bestFitness: null,
      elapsed: 0,
      runningAlgorithm: '',
      analyticalResult: null,
      optimizationResult: null,
      activeResultView: 'optimization',
      mechanism: null,
      couplerCurve: null,
      errorMetrics: null,
      grashofType: null,
      transmissionAngle: null,
      defects: null,
      cognates: null,
      cognatesLoaded: false,
      inversions: {},
      activeInversion: 0,
      _pollTimer: null,
      _pollCount: 0,
      _startTime: null,
    }),
}));

export default useSynthesisStore;
